# Generated by Django 3.2.5 on 2021-07-12 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 12, 18, 19, 57, 261109), verbose_name='日付'),
        ),
    ]
