# Generated by Django 3.2.5 on 2021-07-20 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_slotdata_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotdata',
            options={'verbose_name': 'スロットデータ', 'verbose_name_plural': 'スロットデータ'},
        ),
        migrations.AddField(
            model_name='slotdata',
            name='lastgames',
            field=models.IntegerField(default=111, verbose_name='宵越し'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slotdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 20, 17, 18, 55, 445474), verbose_name='日付'),
        ),
    ]
