# Generated by Django 3.2.5 on 2021-07-20 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20210720_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdata',
            name='bbchance',
            field=models.CharField(default=0.3333333333333333, max_length=10, verbose_name='BB確率'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotdata',
            name='rbchance',
            field=models.CharField(default=0.3333333333333333, max_length=10, verbose_name='RB確率'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotdata',
            name='totalchance',
            field=models.CharField(default=1.0, max_length=10, verbose_name='合成確率'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slotdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 20, 17, 32, 15, 3940), verbose_name='日付'),
        ),
    ]
