# Generated by Django 3.2.5 on 2021-07-21 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_alter_slotdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 17, 56, 47, 163396), verbose_name='日付'),
        ),
        migrations.AlterModelTable(
            name='slotdata',
            table='slotdata',
        ),
    ]
