# Generated by Django 3.2.5 on 2021-07-21 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_alter_slotdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 18, 9, 20, 741039), verbose_name='日付'),
        ),
    ]
