# Generated by Django 3.2.5 on 2021-07-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_alter_slotdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdata',
            name='bbchance',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='bigbonus',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='count',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='lastgames',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='number',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='payout',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='rbchance',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='regularbonus',
        ),
        migrations.RemoveField(
            model_name='slotdata',
            name='totalchance',
        ),
    ]
