# Generated by Django 3.2.5 on 2021-07-21 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_auto_20210721_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdata',
            name='bbchance',
            field=models.CharField(default=1, max_length=10, verbose_name='BB確率'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotdata',
            name='bigbonus',
            field=models.IntegerField(default=1, verbose_name='BB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotdata',
            name='count',
            field=models.IntegerField(default=1, verbose_name='総回転数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AddField(
            model_name='slotdata',
            name='lastgames',
            field=models.IntegerField(default=1, verbose_name='宵越し'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotdata',
            name='memo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='slotdata',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='機種名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotdata',
            name='number',
            field=models.IntegerField(default=1, verbose_name='台番号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotdata',
            name='payout',
            field=models.IntegerField(default=1, verbose_name='差枚数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotdata',
            name='rbchance',
            field=models.CharField(default=1, max_length=10, verbose_name='RB確率'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotdata',
            name='regularbonus',
            field=models.IntegerField(default=1, verbose_name='RB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotdata',
            name='totalchance',
            field=models.CharField(default=1, max_length=10, verbose_name='合成確率'),
            preserve_default=False,
        ),
    ]
